---
language: node_js
node_js:
  - "8"

addons:
  chrome: stable

sudo: false

cache:
  yarn: true

env:
  - EMBER_TRY_SCENARIO=node-tests
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-lts-2.12
  - EMBER_TRY_SCENARIO=ember-lts-2.16
  - EMBER_TRY_SCENARIO=ember-release COVERAGE=true # Only log coverage from release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=with-ember-test-helpers
  - EMBER_TRY_SCENARIO=with-@ember/test-helpers

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

branches:
  only:
    - "master"

before_install:
  - npm install -g bower
  - bower --version

install:
  - bower install
  - yarn install --no-lockfile

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

after_success:
  - if [ -f ./coverage/lcov.info ]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
